name: Build project
on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  project:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build the archive
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        source $CONDA/bin/activate
        conda install -y anaconda-project
        [[ "$GITHUB_REF" == refs/tags/* ]] && suffix=-$GITHUB_REF_NAME
        [[ -z "$GITHUB_HEAD_REF" ]] || suffix=-test
        anaconda-project archive rstudio-installer${suffix}.tar.bz2
    - name: Upload archive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      run: aws s3 cp rstudio-installer*.tar.bz2 s3://airgap.svc.anaconda.com/misc/ --acl public-read --region us-east-1
